### ISSUE TITLE
Syntax error: Unknown sub-command: 'execute'

### ISSUE THREAD

**Issue by Kamilius** [chiefy/karma-virtualbox-launcher#7]
I have an error, specified as an issue title, while trying to run tests using this package. After some "googling" I've found an info, that 'execute' command has been depricated and suggestion to use 'run' instead:
http://stackoverflow.com/questions/33471119/unknown-sub-command-execute-when-using-guestcontrol-option

**Comment by Kamilius** [comment]
Closed as a node-virtualbox issue

**Comment by chiefy** [comment]
👍 thanks for the note - haven't updated this in a while.
